<?php

return [
    'default' => 'general_maritime',

    'templates' => [
        'freight_forwarding' => [
            'name' => 'Freight Forwarder',
            'description' => 'For air, ocean, road, customs, and rate-driven forwarding teams.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'rates', 'quotes', 'shipments', 'carriers', 'bookings', 'costings', 'invoices'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Qualification',
                    'Sales Qualified' => 'Quote Ready',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Enquiry Received',
                    'Proposal Sent' => 'Quote Sent',
                    'Closed Won' => 'Booked',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Rates Collected',
                    'Decision Making' => 'Customer Review',
                    'Project delay' => 'Shipment Pending',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'No buying window',
                ],
                'lead_sources' => ['Email', 'Google Ads', 'Website Quote Form', 'Website Contact Form', 'Referral', 'Partner'],
                'lead_services' => ['Air Freight', 'Ocean Freight', 'Road Freight', 'Customs Clearance', 'Warehousing', 'Project Cargo'],
            ],
        ],
        'container_conversion' => [
            'name' => 'Container Conversion Company',
            'description' => 'For project-based container conversion, fabrication, and delivery teams.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'projects', 'drawings', 'delivery_tracking'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Initial Review',
                    'Sales Qualified' => 'Project Qualified',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Initial Brief',
                    'Proposal Sent' => 'Proposal Sent',
                    'Closed Won' => 'Project Awarded',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Drawings Submitted',
                    'Decision Making' => 'Technical Review',
                    'Project delay' => 'Project Delayed',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'Budget mismatch',
                ],
                'lead_sources' => ['Email', 'Website Quote Form', 'Website Contact Form', 'Google Ads', 'Referral'],
                'lead_services' => ['Container Conversion', 'Custom Fabrication', 'Design & Drawings', 'Site Installation', 'Modified Containers'],
            ],
        ],
        'ship_chandling' => [
            'name' => 'Ship Chandling',
            'description' => 'For vessel supply, requisitions, and urgent port-call delivery operations.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'vessel_calls', 'supply_orders', 'delivery_tasks'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Active Enquiry',
                    'Sales Qualified' => 'Requisition Ready',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Vessel Enquiry',
                    'Proposal Sent' => 'Quote Sent',
                    'Closed Won' => 'Supplied',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Requisition Received',
                    'Decision Making' => 'Delivery Confirmation',
                    'Project delay' => 'Delivery Pending',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'Out of delivery window',
                ],
                'lead_sources' => ['Email', 'Port Agent', 'Referral', 'Website Contact Form', 'Direct Call'],
                'lead_services' => ['Provisions', 'Deck Stores', 'Engine Stores', 'Cabin Stores', 'Safety Equipment', 'Spare Parts'],
            ],
        ],
        'shipping_liner' => [
            'name' => 'Shipping Liner',
            'description' => 'For liner bookings, customer accounts, and slot-allocation driven sales.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'bookings', 'sailings', 'customer_accounts'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Booking Review',
                    'Sales Qualified' => 'Space Qualified',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Booking Request',
                    'Proposal Sent' => 'Offer Sent',
                    'Closed Won' => 'Booked',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Space Pending',
                    'Decision Making' => 'Customer Confirmation',
                    'Project delay' => 'Sailing Deferred',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'No vessel coverage',
                ],
                'lead_sources' => ['Email', 'Sales Team', 'Website Contact Form', 'Referral', 'Partner'],
                'lead_services' => ['Container Shipping', 'Reefer Booking', 'Out of Gauge', 'Slot Allocation', 'Contract Rates'],
            ],
        ],
        'ship_management' => [
            'name' => 'Ship Management Company',
            'description' => 'For technical, crewing, procurement, and owner management relationships.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'fleet', 'technical_management', 'crewing'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Management Review',
                    'Sales Qualified' => 'Owner Qualified',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Management Enquiry',
                    'Proposal Sent' => 'Proposal Sent',
                    'Closed Won' => 'Contract Signed',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Technical Review',
                    'Decision Making' => 'Owner Review',
                    'Project delay' => 'Handover Pending',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'Fleet mismatch',
                ],
                'lead_sources' => ['Email', 'Referral', 'Website Contact Form', 'Conference', 'Partner'],
                'lead_services' => ['Technical Management', 'Crew Management', 'Procurement', 'Vessel Accounting', 'HSQE Management'],
            ],
        ],
        'container_trading_leasing' => [
            'name' => 'Container Trading / Leasing',
            'description' => 'For stock-led container sales, leasing, depot, and asset-allocation workflows.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports', 'inventory', 'leasing', 'depots'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'Commercial Review',
                    'Sales Qualified' => 'Stock Qualified',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Asset Enquiry',
                    'Proposal Sent' => 'Offer Sent',
                    'Closed Won' => 'Deal Closed',
                    'Closed Lost' => 'Lost',
                    'No response' => 'No Response',
                    'Drawings submitted' => 'Stock Check',
                    'Decision Making' => 'Commercial Review',
                    'Project delay' => 'Unit Allocation Pending',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                    'No stock available',
                ],
                'lead_sources' => ['Email', 'Website Quote Form', 'Google Ads', 'Referral', 'Broker'],
                'lead_services' => ['Container Sales', 'Container Leasing', 'Storage', 'Depot Handling', 'Used Container Supply'],
            ],
        ],
        'general_maritime' => [
            'name' => 'General Maritime',
            'description' => 'A flexible CRM mode for maritime companies with a lighter sales workflow.',
            'modules' => ['leads', 'opportunities', 'contacts', 'customers', 'sources', 'analytics', 'access', 'settings', 'exports'],
            'vocabulary' => [
                'lead_status_labels' => [
                    'In-progress' => 'In-progress',
                    'Sales Qualified' => 'Sales Qualified',
                    'Disqualified' => 'Disqualified',
                ],
                'opportunity_stage_labels' => [
                    'Initial Contact' => 'Initial Contact',
                    'Proposal Sent' => 'Proposal Sent',
                    'Closed Won' => 'Closed Won',
                    'Closed Lost' => 'Closed Lost',
                    'No response' => 'No response',
                    'Drawings submitted' => 'Drawings submitted',
                    'Decision Making' => 'Decision Making',
                    'Project delay' => 'Project delay',
                ],
                'disqualification_reasons' => [
                    'No Answer (ONLY SYSTEM)',
                    'Mismatch of Needs',
                    'Duplicate Lead',
                    'Geo Limitations',
                ],
                'lead_sources' => ['Email', 'Google Ads', 'Website Quote Form', 'Website Contact Form', 'Referral'],
                'lead_services' => ['Maritime Services', 'Freight Services', 'Container Conversion', 'Port Services', 'Technical Services'],
            ],
        ],
    ],
];
